[package]
name = "snake"
version = "0.1.0"
authors = ["jannes <jannesdrijkoningen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32"
rand = "0.6.5"